version: '3.5'

networks:
    dev:
        driver: bridge

services:
  api1: # API - Instância 01
    image: docker.io/library/rinhadebackend
    hostname: api1
    depends_on:
      - app_db
    expose:
      - "8080"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'
    networks:
        - dev

  api2: # API - Instância 01
    image: docker.io/library/rinhadebackend
    hostname: api2
    depends_on:
      - app_db
    expose:
      - "8080"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'
    networks:
        - dev

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
    build:
      context: Dockerfile-nginx
    depends_on:
      - api1
      - api2
    ports:
      - "9999:80"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'
    networks:
        - dev

  app_db: # Banco de dados
   container_name: app_db
   image: postgres
   deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1.5GB'
   environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres321
        - POSTGRES_DB=dbdarinha
   ports:
    - "5433:5432" 
   networks:
        - dev